[supervisord]
nodaemon=true

[program:api]
command=uvicorn app:app --host 0.0.0.0 --port 8080
autorestart=true
startretries=999
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr

[program:auto_loop]
command=python control/run_autoloop.py
autorestart=true
startretries=999
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
